name: macOS release

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

    - name: Install release components
      run: rustup component add clippy rustfmt

    - name: Build release
      run: cargo build --release

    - name: Compress binary
      run: |
        mkdir -p release
        cp target/release/prompt release/
        tar czf release/prompt-macos.tar.gz -C release prompt

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: prompt-macos
        path: release/prompt-macos.tar.gz
        retention-days: 5
